# Generated by Django 5.0.2 on 2024-04-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0002_forms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='datum',
            new_name='Prüfungsdatum',
        ),
    ]
