# Generated by Django 5.0.2 on 2024-04-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0003_rename_datum_forms_prüfungsdatum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forms',
            new_name='Prüflinge',
        ),
    ]
