# Generated by Django 5.0.2 on 2024-04-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0005_remove_prüflinge_vorname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prüflinge',
            old_name='Prüfungsdatum',
            new_name='prüfungsdatum',
        ),
    ]
