# Generated by Django 5.0.6 on 2024-05-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0007_alter_events_text_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prüflinge',
            name='prüfungsdatum',
            field=models.DateField(default='%d/%m/%Y'),
        ),
    ]
