# Generated by Django 5.0.6 on 2024-05-09 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0013_alter_prüflinge_prüfungsdatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prüflinge',
            name='prüfungsdatum',
            field=models.CharField(default=datetime.datetime(2024, 5, 9, 11, 42, 25, 271301), max_length=255, null=True),
        ),
    ]
