# Generated by Django 5.0.6 on 2024-05-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0014_alter_prüflinge_prüfungsdatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(default='2024-05-09'),
        ),
        migrations.AlterField(
            model_name='prüflinge',
            name='prüfungsdatum',
            field=models.DateField(default='2024-05-09'),
        ),
    ]
