# Generated by Django 5.0.6 on 2024-07-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0015_alter_prüflinge_prüfungsdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='prüflinge',
            name='fl',
            field=models.CharField(default='', max_length=255),
        ),
    ]
