# Generated by Django 5.0.6 on 2024-07-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0016_prüflinge_fl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prüflinge',
            name='fl',
            field=models.CharField(default='Test', max_length=255),
        ),
    ]
