# Generated by Django 5.0.6 on 2024-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0016_alter_events_date_alter_prüflinge_prüfungsdatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prüflinge',
            name='prüfungsdatum',
            field=models.DateField(),
        ),
    ]
