# Generated by Django 5.0.6 on 2024-07-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0017_alter_prüflinge_fl'),
    ]

    operations = [
        migrations.AddField(
            model_name='prüflinge',
            name='uhrzeit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prüflinge',
            name='fl',
            field=models.CharField(max_length=255),
        ),
    ]
