# Generated by Django 5.0.6 on 2024-07-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0018_prüflinge_uhrzeit_alter_prüflinge_fl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prüflinge',
            name='uhrzeit',
        ),
        migrations.AddField(
            model_name='events',
            name='uhrzeit',
            field=models.DateTimeField(null=True),
        ),
    ]
