# Generated by Django 5.0.6 on 2024-07-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0019_remove_prüflinge_uhrzeit_events_uhrzeit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='uhrzeit',
            field=models.TimeField(null=True),
        ),
    ]
