# Generated by Django 5.0.6 on 2024-07-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0020_alter_events_uhrzeit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktuellePrüfungListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fl', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('prüfungsdatum', models.DateField(null=True)),
                ('uhrzeit', models.TimeField(null=True)),
            ],
        ),
    ]
