# Generated by Django 5.0.6 on 2024-07-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0021_aktuelleprüfungliste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prüflinge',
            name='bezahlt',
        ),
    ]
