# Generated by Django 5.0.6 on 2024-07-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0022_remove_prüflinge_bezahlt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='TüvTermine',
        ),
    ]
