# Generated by Django 5.0.6 on 2024-07-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0023_rename_events_tüvtermine'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrüflingeTheorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vorname', models.CharField(max_length=255)),
                ('lernerfolg', models.BigIntegerField()),
                ('anrufdatum', models.DateField(null=True)),
            ],
        ),
    ]
