# Generated by Django 5.0.6 on 2025-02-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschulemanager_fullstack', '0024_prüflingetheorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockUnterricht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text_event', models.TextField()),
                ('uhrzeit', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockUnterrichtSchueler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vorname', models.CharField(max_length=255)),
                ('thema', models.CharField(max_length=255)),
                ('datum', models.DateField()),
                ('uhrzeit', models.TimeField(null=True)),
            ],
        ),
    ]
